# Generated by Django 5.2.5 on 2025-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvtfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='deposited_by',
            field=models.CharField(default='Admin JCO', max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_description',
            field=models.CharField(default='Income from Unit Canteen', max_length=400),
        ),
    ]
