# Generated by Django 5.2.5 on 2025-08-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvtfund', '0002_fund_deposited_by_fund_fund_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='deposit_date',
            field=models.DateField(),
        ),
    ]
